version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      # - <port on localhost>:<port on container>
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=fastapi-prod
      - SECRET_KEY=uewuredhfjkndfjheru934022-093uy824jlasijiqqwy8990132jsdkjmfcv0u4pgu94u934892034-9234r
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi-prod

    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
