"""removed phone number from user

Revision ID: 82d2ccf847e9
Revises: e3b45a8e6b4c
Create Date: 2022-05-18 10:29:45.039393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d2ccf847e9'
down_revision = 'e3b45a8e6b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
